### ISSUE TITLE
[feature] add filter

### ISSUE THREAD

**Issue by garak** [babobski/FontAwesome#1]
I just discovered this addon and I think it's great. Anyway, after few times I tried to use it, I realized that a miss a filter, just like the one to search in [Font Awesome website](http://fortawesome.github.io/Font-Awesome/icons/).
Whit such feature, this addon would be perfect! :rocket:

**Comment by babobski** [comment]
Thanks for the suggestion, it's something i also would love to see, will be looking in to it..

**Comment by babobski** [comment]
Added it in the latest release
